#include "engine_export/TrainerExport.h"

#include <algorithm>
#include <cctype>
#include <cstdlib>
#include <fstream>
#include <sstream>

namespace ire::engine_export {

namespace {

template <typename T>
using Result = infra::Result<T>;

std::string escapeForCpp(const std::string& text) {
    std::string out;
    for (const char c : text) {
        if (c == '\\' || c == '"') {
            out.push_back('\\');
            out.push_back(c);
        } else if (c == '\n' || c == '\r' || c == '\t') {
            out.push_back(' ');
        } else {
            out.push_back(c);
        }
    }
    return out;
}

std::string byteArray(const std::vector<std::uint8_t>& bytes) {
    std::ostringstream out;
    for (std::size_t i = 0; i < bytes.size(); ++i) {
        if (i > 0) {
            out << ", ";
        }
        out << "0x" << std::hex << std::uppercase;
        if (bytes[i] < 0x10) {
            out << '0';
        }
        out << static_cast<unsigned>(bytes[i]) << std::dec << std::nouppercase;
    }
    return out.str();
}

// F1..F12 as a virtual key code, or 0 for anything else. The trainer only
// supports the function keys because that is what the address list registers,
// and inventing a wider mapping here would generate hotkeys the table cannot
// express.
int virtualKey(const std::string& hotkey) {
    if (hotkey.size() < 2 || (hotkey[0] != 'F' && hotkey[0] != 'f')) {
        return 0;
    }
    const auto number = std::atoi(hotkey.c_str() + 1);
    if (number < 1 || number > 12) {
        return 0;
    }
    return 0x70 + (number - 1); // VK_F1
}

} // namespace

std::string TrainerExport::identifier(const std::string& name) {
    std::string out;
    for (const char c : name) {
        if (std::isalnum(static_cast<unsigned char>(c)) != 0) {
            out.push_back(c);
        } else if (c == ' ' || c == '-' || c == '_') {
            out.push_back('_');
        }
    }
    // Trim the underscores a name like "My Trainer " would otherwise end with,
    // because "My_Trainer_" is a worse target name than "My_Trainer".
    while (!out.empty() && out.back() == '_') {
        out.pop_back();
    }
    while (!out.empty() && out.front() == '_') {
        out.erase(out.begin());
    }
    if (out.empty()) {
        return "Trainer";
    }
    if (std::isdigit(static_cast<unsigned char>(out.front())) != 0) {
        out.insert(out.begin(), '_');
    }
    return out;
}

std::vector<GeneratedFile> TrainerExport::generate(const TrainerOptions& options) {
    const auto project = identifier(options.name);
    const auto processName = domain::narrow(options.processName);

    // Only entries that have something to write. An address with no recorded
    // value is a thing to watch rather than a thing to change, and the trainer
    // reports those instead of silently dropping them.
    std::vector<domain::AddressEntry> cheats;
    std::vector<domain::AddressEntry> watches;
    for (const auto& entry : options.entries) {
        if (entry.frozenValue.empty()) {
            watches.push_back(entry);
        } else {
            cheats.push_back(entry);
        }
    }

    std::ostringstream source;
    source
        << "// " << project << " -- generated by Pointer Lab.\n"
        << "//\n"
        << "// An *external* trainer: it never runs inside the game. It opens a handle to\n"
        << "// the process and reads and writes its memory from outside, which is the\n"
        << "// simplest kind to understand and the easiest to get right.\n"
        << "//\n"
        << "// Read it before you run it. Everything here is ordinary Win32 -- there is no\n"
        << "// library and nothing hidden, and the whole point of generating source rather\n"
        << "// than an executable is that you can see what it is about to do.\n"
        << "//\n"
        << "// Target: " << escapeForCpp(processName) << " (" << domain::bitnessName(options.bitness)
        << ")\n"
        << "//\n"
        << "// Built for " << domain::bitnessName(options.bitness)
        << ", and it has to be: a pointer chain steps by the width of a pointer in\n"
        << "// the *target*, and this program reads them into its own uintptr_t.\n"
        << "\n"
        << "#include <Windows.h>\n"
        << "#include <tlhelp32.h>\n"
        << "\n"
        << "#include <cstdint>\n"
        << "#include <cstdio>\n"
        << "#include <cstring>\n"
        << "#include <vector>\n"
        << "\n"
        << "namespace {\n"
        << "\n"
        << "// ---------------------------------------------------------------------------\n"
        << "// Finding the process\n"
        << "// ---------------------------------------------------------------------------\n"
        << "\n"
        << "DWORD findProcess(const wchar_t* name) {\n"
        << "    HANDLE snapshot = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);\n"
        << "    if (snapshot == INVALID_HANDLE_VALUE) {\n"
        << "        return 0;\n"
        << "    }\n"
        << "    PROCESSENTRY32W entry{};\n"
        << "    entry.dwSize = sizeof(entry);\n"
        << "    DWORD pid = 0;\n"
        << "    if (Process32FirstW(snapshot, &entry)) {\n"
        << "        do {\n"
        << "            if (_wcsicmp(entry.szExeFile, name) == 0) {\n"
        << "                pid = entry.th32ProcessID;\n"
        << "                break;\n"
        << "            }\n"
        << "        } while (Process32NextW(snapshot, &entry));\n"
        << "    }\n"
        << "    CloseHandle(snapshot);\n"
        << "    return pid;\n"
        << "}\n"
        << "\n"
        << "// The base a module happens to be loaded at *this run*. ASLR puts it\n"
        << "// somewhere different every time, which is exactly why the addresses below\n"
        << "// are stored as an offset within a module rather than as absolute numbers.\n"
        << "uintptr_t moduleBase(DWORD pid, const wchar_t* name) {\n"
        << "    HANDLE snapshot = CreateToolhelp32Snapshot(TH32CS_SNAPMODULE | TH32CS_SNAPMODULE32, pid);\n"
        << "    if (snapshot == INVALID_HANDLE_VALUE) {\n"
        << "        return 0;\n"
        << "    }\n"
        << "    MODULEENTRY32W entry{};\n"
        << "    entry.dwSize = sizeof(entry);\n"
        << "    uintptr_t base = 0;\n"
        << "    if (Module32FirstW(snapshot, &entry)) {\n"
        << "        do {\n"
        << "            if (_wcsicmp(entry.szModule, name) == 0) {\n"
        << "                base = reinterpret_cast<uintptr_t>(entry.modBaseAddr);\n"
        << "                break;\n"
        << "            }\n"
        << "        } while (Module32NextW(snapshot, &entry));\n"
        << "    }\n"
        << "    CloseHandle(snapshot);\n"
        << "    return base;\n"
        << "}\n"
        << "\n"
        << "// ---------------------------------------------------------------------------\n"
        << "// The cheats\n"
        << "// ---------------------------------------------------------------------------\n"
        << "\n"
        << "struct Cheat {\n"
        << "    const wchar_t* description;\n"
        << "    int hotkey;                  // VK_F1..VK_F12, or 0 for always on\n"
        << "    const wchar_t* moduleName;   // nullptr when the address is absolute\n"
        << "    uintptr_t base;              // offset within that module, or the address itself\n"
        << "    const ptrdiff_t* offsets;    // the chain, one dereference per offset\n"
        << "    size_t offsetCount;\n"
        << "    const unsigned char* value;\n"
        << "    size_t valueSize;\n"
        << "    bool enabled;\n"
        << "};\n"
        << "\n";

    // Per-cheat data.
    for (std::size_t i = 0; i < cheats.size(); ++i) {
        const auto& entry = cheats[i];
        source << "// " << escapeForCpp(entry.description.empty() ? std::string("entry") : entry.description)
               << " -- " << domain::formatValue(entry.type, entry.frozenValue) << " ("
               << domain::valueTypeName(entry.type) << ")\n"
               << "const unsigned char cheat" << i << "_value[] = { " << byteArray(entry.frozenValue)
               << " };\n";
        if (entry.chain && !entry.chain->offsets.empty()) {
            source << "const ptrdiff_t cheat" << i << "_offsets[] = { ";
            for (std::size_t j = 0; j < entry.chain->offsets.size(); ++j) {
                if (j > 0) {
                    source << ", ";
                }
                source << "0x" << std::hex << std::uppercase
                       << static_cast<std::uintptr_t>(entry.chain->offsets[j]) << std::dec
                       << std::nouppercase;
            }
            source << " };\n";
        }
        source << "\n";
    }

    source << "Cheat g_cheats[] = {\n";
    for (std::size_t i = 0; i < cheats.size(); ++i) {
        const auto& entry = cheats[i];
        const bool rooted = entry.chain && entry.chain->moduleRooted();
        const bool hasOffsets = entry.chain && !entry.chain->offsets.empty();
        const auto key = virtualKey(entry.hotkey);
        source << "    { L\""
               << escapeForCpp(entry.description.empty() ? domain::toHex(entry.address) : entry.description)
               << "\", ";
        if (key != 0) {
            source << "0x" << std::hex << std::uppercase << key << std::dec << std::nouppercase;
        } else {
            source << "0";
        }
        source << ", ";
        if (rooted) {
            source << "L\"" << escapeForCpp(domain::narrow(entry.chain->moduleName)) << "\", 0x" << std::hex
                   << std::uppercase << entry.chain->moduleOffset << std::dec << std::nouppercase;
        } else {
            const auto absolute = entry.chain ? entry.chain->moduleOffset : entry.address;
            source << "nullptr, 0x" << std::hex << std::uppercase << absolute << std::dec
                   << std::nouppercase;
        }
        source << ", ";
        if (hasOffsets) {
            source << "cheat" << i << "_offsets, " << entry.chain->offsets.size();
        } else {
            source << "nullptr, 0";
        }
        source << ", cheat" << i << "_value, sizeof(cheat" << i << "_value), false }";
        if (i + 1 < cheats.size()) {
            source << ',';
        }
        if (!rooted) {
            source << "  // absolute address: valid only while this run of the game lasts";
        }
        source << '\n';
    }
    source << "};\n"
           << "\n";

    source
        << "// Walks the chain: read a pointer at the base, add the first offset, read a\n"
        << "// pointer there, and so on. The last offset is added without a read, because\n"
        << "// the value itself is not a pointer.\n"
        << "uintptr_t resolve(HANDLE process, DWORD pid, const Cheat& cheat) {\n"
        << "    uintptr_t address = cheat.base;\n"
        << "    if (cheat.moduleName != nullptr) {\n"
        << "        const uintptr_t base = moduleBase(pid, cheat.moduleName);\n"
        << "        if (base == 0) {\n"
        << "            return 0;\n"
        << "        }\n"
        << "        address += base;\n"
        << "    }\n"
        << "    for (size_t i = 0; i < cheat.offsetCount; ++i) {\n"
        << "        uintptr_t next = 0;\n"
        << "        SIZE_T read = 0;\n"
        << "        if (!ReadProcessMemory(process, reinterpret_cast<LPCVOID>(address), &next,\n"
        << "                               sizeof(next), &read) ||\n"
        << "            read != sizeof(next)) {\n"
        << "            return 0;\n"
        << "        }\n"
        << "        address = next + static_cast<uintptr_t>(cheat.offsets[i]);\n"
        << "    }\n"
        << "    return address;\n"
        << "}\n"
        << "\n"
        << "} // namespace\n"
        << "\n"
        << "int main() {\n"
        << "    const wchar_t* processName = L\"" << escapeForCpp(processName) << "\";\n"
        << "    std::wprintf(L\"" << escapeForCpp(project) << " -- waiting for %s\\n\", processName);\n"
        << "\n"
        << "    DWORD pid = 0;\n"
        << "    while ((pid = findProcess(processName)) == 0) {\n"
        << "        Sleep(500);\n"
        << "    }\n"
        << "\n"
        << "    // PROCESS_ALL_ACCESS is more than this needs. The three rights below are\n"
        << "    // the whole of it, and asking for only what you use is the difference\n"
        << "    // between a trainer that works without administrator and one that does not.\n"
        << "    HANDLE process = OpenProcess(PROCESS_VM_READ | PROCESS_VM_WRITE | PROCESS_VM_OPERATION |\n"
        << "                                     PROCESS_QUERY_LIMITED_INFORMATION,\n"
        << "                                 FALSE, pid);\n"
        << "    if (process == nullptr) {\n"
        << "        std::wprintf(L\"Could not open the process (error %lu). Try running as "
           "administrator.\\n\",\n"
        << "                     GetLastError());\n"
        << "        return 1;\n"
        << "    }\n"
        << "    std::wprintf(L\"Attached to pid %lu.\\n\\n\", pid);\n"
        << "\n";

    if (cheats.empty()) {
        source << "    std::wprintf(L\"This table had no frozen values, so there is nothing to "
                  "write.\\n\");\n";
    } else {
        source << "    for (const Cheat& cheat : g_cheats) {\n"
               << "        if (cheat.hotkey != 0) {\n"
               << "            std::wprintf(L\"  F%d  %s\\n\", cheat.hotkey - 0x70 + 1, cheat.description);\n"
               << "        } else {\n"
               << "            std::wprintf(L\"  on  %s\\n\", cheat.description);\n"
               << "        }\n"
               << "    }\n"
               << "    std::wprintf(L\"\\nPress the key to toggle. Ctrl+C to quit.\\n\");\n";
    }

    source
        << "\n"
        << "    // Twenty writes a second. Slower and a value the game recomputes every\n"
        << "    // frame visibly fights back between writes; faster spends the difference\n"
        << "    // in WriteProcessMemory for no visible gain.\n"
        << "    bool previousKey[256] = {};\n"
        << "    for (;;) {\n"
        << "        for (Cheat& cheat : g_cheats) {\n"
        << "            if (cheat.hotkey != 0) {\n"
        << "                const bool down = (GetAsyncKeyState(cheat.hotkey) & 0x8000) != 0;\n"
        << "                // Edge triggered: holding the key must toggle once, not sixty\n"
        << "                // times a second.\n"
        << "                if (down && !previousKey[cheat.hotkey]) {\n"
        << "                    cheat.enabled = !cheat.enabled;\n"
        << "                    std::wprintf(L\"%s: %s\\n\", cheat.description, cheat.enabled ? L\"on\" : "
           "L\"off\");\n"
        << "                }\n"
        << "                previousKey[cheat.hotkey] = down;\n"
        << "            } else {\n"
        << "                cheat.enabled = true;\n"
        << "            }\n"
        << "\n"
        << "            if (!cheat.enabled) {\n"
        << "                continue;\n"
        << "            }\n"
        << "            const uintptr_t address = resolve(process, pid, cheat);\n"
        << "            if (address == 0) {\n"
        << "                continue;\n"
        << "            }\n"
        << "            SIZE_T written = 0;\n"
        << "            WriteProcessMemory(process, reinterpret_cast<LPVOID>(address), cheat.value,\n"
        << "                               cheat.valueSize, &written);\n"
        << "        }\n"
        << "\n"
        << "        if (WaitForSingleObject(process, 50) == WAIT_OBJECT_0) {\n"
        << "            std::wprintf(L\"The game exited.\\n\");\n"
        << "            break;\n"
        << "        }\n"
        << "    }\n"
        << "\n"
        << "    CloseHandle(process);\n"
        << "    return 0;\n"
        << "}\n";

    std::ostringstream cmake;
    cmake << "cmake_minimum_required(VERSION 3.20)\n"
          << "project(" << project << " CXX)\n"
          << "\n"
          << "# Must match the target. A 64-bit trainer reads 8-byte pointers, and a\n"
          << "# 32-bit game does not have any.\n"
          << "#   cmake -S . -B build -A "
          << (options.bitness == domain::Bitness::X64 ? "x64" : "Win32") << "\n"
          << "#   cmake --build build --config Release\n"
          << "\n"
          << "add_executable(" << project << " main.cpp)\n"
          << "target_compile_features(" << project << " PRIVATE cxx_std_17)\n"
          << "target_compile_definitions(" << project << " PRIVATE UNICODE _UNICODE "
          << "WIN32_LEAN_AND_MEAN NOMINMAX)\n"
          << "if(MSVC)\n"
          << "    target_compile_options(" << project << " PRIVATE /W4)\n"
          << "    # Static CRT, so the built trainer runs without the VC++ redistributable.\n"
          << "    set_property(TARGET " << project
          << " PROPERTY MSVC_RUNTIME_LIBRARY \"MultiThreaded$<$<CONFIG:Debug>:Debug>\")\n"
          << "endif()\n";

    std::ostringstream readme;
    readme << "# " << project << "\n"
           << "\n"
           << "An external trainer for `" << processName << "`, generated by Pointer Lab from "
           << options.entries.size() << " address list entr"
           << (options.entries.size() == 1 ? "y" : "ies") << ".\n"
           << "\n"
           << "## Build\n"
           << "\n"
           << "```\n"
           << "cmake -S . -B build -A " << (options.bitness == domain::Bitness::X64 ? "x64" : "Win32")
           << "\n"
           << "cmake --build build --config Release\n"
           << "```\n"
           << "\n"
           << "The architecture is not optional. A pointer chain steps by the width of a\n"
           << "pointer in the target, and this trainer reads each hop into its own\n"
           << "`uintptr_t`; built for the wrong width it reads two pointers as one, every\n"
           << "chain breaks at the first hop, and nothing reports an error.\n"
           << "\n"
           << "## What it does\n"
           << "\n";

    if (cheats.empty()) {
        readme << "Nothing yet. None of the exported entries had a value recorded, so there is\n"
               << "nothing for the trainer to write. Freeze the values you want in Pointer Lab\n"
               << "first -- the frozen value is what gets exported -- and export again.\n\n";
    } else {
        readme << "| Key | Cheat | Address | Value |\n"
               << "| --- | --- | --- | --- |\n";
        for (const auto& entry : cheats) {
            const auto key = virtualKey(entry.hotkey);
            readme << "| " << (key != 0 ? entry.hotkey : std::string("always on")) << " | "
                   << (entry.description.empty() ? domain::toHex(entry.address) : entry.description)
                   << " | ";
            if (entry.chain && entry.chain->moduleRooted()) {
                readme << "`" << domain::narrow(entry.chain->moduleName) << "+0x"
                       << std::hex << entry.chain->moduleOffset << std::dec << "`";
                for (const auto offset : entry.chain->offsets) {
                    readme << " -> `+0x" << std::hex << static_cast<std::uintptr_t>(offset) << std::dec
                           << "`";
                }
            } else {
                readme << "`" << domain::toHex(entry.address) << "` (absolute)";
            }
            readme << " | " << domain::formatValue(entry.type, entry.frozenValue) << " ("
                   << domain::valueTypeName(entry.type) << ") |\n";
        }
        readme << "\n";
    }

    if (!watches.empty()) {
        readme << "## Not exported\n"
               << "\n"
               << std::to_string(watches.size()) << " entr"
               << (watches.size() == 1 ? "y" : "ies")
               << " had no recorded value and so nothing to write:\n\n";
        for (const auto& entry : watches) {
            readme << "- " << (entry.description.empty() ? domain::toHex(entry.address) : entry.description)
                   << "\n";
        }
        readme << "\nAn entry's exported value is the one it was frozen at. Freeze it in Pointer\n"
               << "Lab and export again.\n\n";
    }

    bool anyAbsolute = false;
    for (const auto& entry : cheats) {
        if (!entry.chain || !entry.chain->moduleRooted()) {
            anyAbsolute = true;
            break;
        }
    }
    if (anyAbsolute) {
        readme << "## A warning about the absolute addresses\n"
               << "\n"
               << "Some entries above are plain addresses rather than `module+offset` chains.\n"
               << "Those are valid only for the run of the game they were found in: ASLR puts\n"
               << "everything somewhere else next time, and the trainer will happily write to\n"
               << "whatever now lives there. Find a pointer chain for them -- that is what the\n"
               << "pointer scanner is for -- and export again.\n"
               << "\n";
    }

    readme << "## Read it first\n"
           << "\n"
           << "`main.cpp` is about 200 lines of ordinary Win32. It opens the process,\n"
           << "looks up a module base, walks a pointer chain one dereference at a time,\n"
           << "and writes bytes twenty times a second. There is no library and nothing\n"
           << "hidden. That is the point of generating source instead of an executable:\n"
           << "a trainer you have read is a trainer you understand, and one you have not\n"
           << "is a program of unknown provenance you are about to point at your own\n"
           << "machine.\n";

    return {
        {"main.cpp", source.str()},
        {"CMakeLists.txt", cmake.str()},
        {"README.md", readme.str()},
    };
}

infra::Result<std::size_t> TrainerExport::write(const std::filesystem::path& directory,
                                                const TrainerOptions& options) {
    std::error_code ec;
    std::filesystem::create_directories(directory, ec);
    if (!std::filesystem::is_directory(directory, ec)) {
        return Result<std::size_t>::fail("Could not create " + directory.string() + ".");
    }

    const auto files = generate(options);
    // Checked before anything is written, so a collision on the third file does
    // not leave the first two behind.
    for (const auto& file : files) {
        if (std::filesystem::exists(directory / file.name, ec)) {
            return Result<std::size_t>::fail(
                (directory / file.name).string() +
                " already exists. Export into an empty directory: the likeliest reason for a collision is a "
                "trainer you have since edited.");
        }
    }

    for (const auto& file : files) {
        std::ofstream out(directory / file.name, std::ios::binary | std::ios::trunc);
        if (!out) {
            return Result<std::size_t>::fail("Could not write " + (directory / file.name).string() + ".");
        }
        out << file.contents;
        out.flush();
        if (!out) {
            return Result<std::size_t>::fail("Could not finish writing " +
                                             (directory / file.name).string() +
                                             " (the disk may be full or read-only).");
        }
    }
    return Result<std::size_t>::ok(files.size());
}

} // namespace ire::engine_export
